import { StyleSheet, Platform } from 'react-native';

export const s = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#060b14",
      },
      flex1: {
        flex: 1,
      },
      root: {
        flex: 1,
        backgroundColor: "#060b14",
      },
      header: {
        paddingTop: Platform.OS === "ios" ? 8 : 12,
        paddingBottom: 14,
        paddingHorizontal: 20,
        backgroundColor: "#060b14",
        borderBottomWidth: 1,
        borderBottomColor: "#0f1f36",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
      },
      headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#e2e8f0",
        letterSpacing: 0.3,
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      headerSub: {
        fontSize: 11,
        color: "#475569",
        marginTop: 2,
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      headerDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#10b981",
      },
      urlBar: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#0c1525",
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#0f1f36",
        gap: 8,
      },
      urlLabel: {
        fontSize: 10,
        color: "#3b82f6",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
        fontWeight: "600",
        letterSpacing: 0.5,
      },
      urlDisplay: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
      },
      urlText: {
        flex: 1,
        fontSize: 12,
        color: "#94a3b8",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      urlEdit: {
        fontSize: 11,
        color: "#3b82f6",
        marginLeft: 8,
      },
      urlInput: {
        flex: 1,
        fontSize: 12,
        color: "#e2e8f0",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
        backgroundColor: "#111827",
        borderRadius: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: "#3b82f6",
      },
      urlInputEditing: {},
      urlBtn: {
        backgroundColor: "#3b82f6",
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 7,
      },
      urlBtnTxt: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "600",
      },
      tabs: {
        flexDirection: "row",
        backgroundColor: "#060b14",
        borderBottomWidth: 1,
        borderBottomColor: "#0f1f36",
      },
      tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: "center",
        borderBottomWidth: 2,
        borderBottomColor: "transparent",
      },
      tabActive: {
        borderBottomColor: "#3b82f6",
      },
      tabText: {
        fontSize: 12,
        color: "#475569",
        fontWeight: "500",
      },
      tabTextActive: {
        color: "#3b82f6",
        fontWeight: "600",
      },
      scrollArea: {
        flex: 1,
      },
      scrollContent: {
        padding: 16,
        paddingBottom: 40,
        rowGap: 16,
      },
      card: {
        backgroundColor: "#0c1525",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#0f1f36",
        padding: 16,
        rowGap: 12,
      },
      cardTitle: {
        fontSize: 13,
        color: "#94a3b8",
        fontWeight: "600",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
        marginBottom: 4,
      },
      cardRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
      },
      methodBadge: {
        fontWeight: "700",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      input: {
        backgroundColor: "#111827",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#1e2d45",
        color: "#e2e8f0",
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
      },
      textArea: {
        minHeight: 70,
        textAlignVertical: "top",
      },
      btn: {
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
      },
      btnPost: { backgroundColor: "#10b981" },
      btnPut: { backgroundColor: "#f59e0b" },
      btnDelete: { backgroundColor: "#ef4444" },
      btnGhost: {
        backgroundColor: "transparent",
        borderWidth: 1,
        borderColor: "#1e2d45",
      },
      btnDisabled: { opacity: 0.4 },
      btnTxt: { color: "#fff", fontWeight: "700", fontSize: 14 },
      smallBtn: {
        borderRadius: 6,
        paddingVertical: 6,
        paddingHorizontal: 14,
        alignItems: "center",
      },
      smallBtnTxt: { color: "#fff", fontSize: 12, fontWeight: "600" },
      ghostBtnTxt: { color: "#64748b", fontSize: 12 },
      fetchBtn: {
        paddingVertical: 6,
        paddingHorizontal: 14,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "#1e3a5f",
      },
      fetchBtnTxt: {
        color: "#3b82f6",
        fontSize: 12,
        fontWeight: "600",
      },
      hint: {
        fontSize: 13,
        color: "#334155",
        lineHeight: 20,
        textAlign: "center",
        marginVertical: 8,
      },
      emptyState: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 32,
        rowGap: 8,
      },
      emptyTitle: {
        fontSize: 16,
        color: "#1e293b",
        fontWeight: "600",
      },
      noteCard: {
        backgroundColor: "#111827",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#1e2d45",
        padding: 12,
        rowGap: 8,
      },
      noteHeader: {
        flexDirection: "row",
        alignItems: "center",
        columnGap: 8,
      },
      noteId: {
        fontSize: 10,
        color: "#334155",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      noteTitle: {
        flex: 1,
        fontSize: 14,
        fontWeight: "600",
        color: "#cbd5e1",
      },
      noteContent: {
        fontSize: 12,
        color: "#475569",
        lineHeight: 18,
      },
      noteActions: {
        flexDirection: "row",
        columnGap: 8,
        marginTop: 4,
      },
      logCard: {
        backgroundColor: "#0c1525",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#0f1f36",
        padding: 12,
        rowGap: 10,
        marginBottom: 12,
      },
      logHeader: {
        flexDirection: "row",
        alignItems: "center",
        columnGap: 8,
        flexWrap: "wrap",
      },
      methodTag: {
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
      },
      methodTagTxt: {
        fontSize: 10,
        fontWeight: "700",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      logPath: {
        flex: 1,
        fontSize: 12,
        color: "#94a3b8",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      statusTag: {
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
      },
      statusTagTxt: {
        fontSize: 10,
        fontWeight: "700",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      logTime: {
        fontSize: 10,
        color: "#334155",
      },
      logSection: { rowGap: 4 },
      logSectionLabel: {
        fontSize: 9,
        color: "#334155",
        fontWeight: "700",
        letterSpacing: 1,
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      logCode: {
        fontSize: 11,
        color: "#64748b",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
        lineHeight: 18,
      },
      snippetBar: {
        backgroundColor: "#060b14",
        borderBottomWidth: 1,
        borderBottomColor: "#0f1f36",
        maxHeight: 48,
      },
      snippetBarContent: {
        paddingHorizontal: 12,
        alignItems: "center",
        columnGap: 8,
        paddingVertical: 10,
      },
      snippetChip: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#0c1525",
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderWidth: 1,
        borderColor: "#0f1f36",
      },
      snippetChipActive: {
        borderColor: "#3b82f6",
        backgroundColor: "#0d1f3c",
      },
      snippetChipTxt: {
        fontSize: 11,
        color: "#475569",
        fontWeight: "600",
      },
      snippetChipTxtActive: { color: "#93c5fd" },
      snippetMethod: {
        fontSize: 11,
        fontWeight: "700",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
      codeBlock: {
        backgroundColor: "#060b14",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#0f1f36",
        padding: 14,
      },
      codeText: {
        fontSize: 12,
        color: "#7dd3fc",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
        lineHeight: 22,
      },
      stepRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        columnGap: 12,
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: "#0f1f36",
      },
      stepBadge: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: "#1e3a5f",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 2,
      },
      stepBadgeTxt: {
        fontSize: 11,
        fontWeight: "700",
        color: "#3b82f6",
      },
      stepNote: {
        fontSize: 13,
        color: "#64748b",
        marginBottom: 3,
      },
      stepCmd: {
        fontSize: 12,
        color: "#7dd3fc",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      },
    });
